indentation

diff --git a/tp-sample-app/environments/ci/tasks/10-ibm-gitops.yaml b/tp-sample-app/environments/ci/tasks/10-ibm-gitops.yaml
--- a/tp-sample-app/environments/ci/tasks/10-ibm-gitops.yaml
+++ b/tp-sample-app/environments/ci/tasks/10-ibm-gitops.yaml
@@ -123,12 +123,12 @@ spec:
           fi
 
           export CHART_ROOT=$(find . -name chart)
-          echo "CHART_ROOT: $CHART_ROOT"
+           echo "CHART_ROOT: $CHART_ROOT"
 
           FILE_NUM=$(find . -name 'Chart*.yaml' |wc -l)
           if [[ "${FILE_NUM}" -gt 1 ]]; then
-          echo "Error: Found >1 Chart*.yaml"
-          exit 1
+           echo "Error: Found >1 Chart*.yaml"
+           exit 1
           fi
 
           export CHART=$(find . -name 'Chart*.yaml')
